export const ADD_ITEM_IN_CART_BEFOR_LOGIN = "ADD_ITEM_IN_CART_BEFOR_LOGIN";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_ITEM_IN_WISHLIST_BEFOR_LOGIN =
  "ADD_ITEM_IN_WISHLIST_BEFOR_LOGIN";
